# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "f6dd07c3caa2c5176b8ce5a19f3e1ba0984db02596ab18eac365d29012887d7d"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8ddee1f7955113f08842d7f53545d891a9436217addf806e0599940733260eed"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1053fc765620005c898437df17b129c76aab4ab2516ff62f79ca46327335490"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9d44af5d5603a699b3fda6dda9b330e81cfb30d1fd428a5f2d891f340749411a"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/andresbott/dibs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "dibs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibs"]
    end
  end

  # No zap stanza required

end
