# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b714fa118d1ba748b9861e212e1d2735a3d4a45739327179dcbd29176db0c05e"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ae8e71035cbcb8d6d5396f3e4c668d4cd1f83f01d8e02aa5b0ceeb2dfe7e3746"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "121174a9e30453a60d1774d46b98c107b8f3c4763761c30850cc62cb713a7d4e"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e2b7314c56c4884d21752d19d10e233cf3314792e96560b86105b3e8ce99bef4"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/andresbott/dibs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "dibs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibs"]
    end
  end

  # No zap stanza required

end
