# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "06e4f3b9842a8a72a86bc02970d0c6081f5085a69685cc68b55bc987611feea1"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e8afe7ad4adeda0519eb8c2002949f4bf0183361fadd5e27419e07e4b7e50115"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aaef26bc4a0b88a4caba5fc500d62bea8958cac96bc06373e400464497987654"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d125ffd4e3ce0bced6b17bf18ceddee8b1f1d1fe7db2ea825ea4fef730108c64"
      url "https://github.com/andresbott/dibs/releases/download/v#{version}/dibs_Linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/andresbott/dibs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "dibs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibs"]
    end
  end

  # No zap stanza required

end
